"""
Given two strings s and t. String t is generated by shuffling string s and then adding one more letter at a random position. 
Return the letter that was added to t.

Example:

s = 'Python'

t = 'thnobPy'

Expected output = 'b'
"""

def new_letter(s,t):
    new = ""
    for i in t:
        if i in s:
            pass
        else:
            new = new+i
    return new
